name: socat

on:
  workflow_dispatch

jobs:
  build-aarch64:
    name: Build socat AARCH64
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build socat in Docker container
        run: |
          docker run --rm \
            -v "$PWD":/src \
            -w /src \
            muslcc/x86_64:aarch64-linux-musl \
            sh -c "apk update && apk add bash curl rsync util-linux && bash build/install_deps_alpine.sh && ./build/targets/build_socat.sh aarch64"

      - name: Get version info
        id: get_version
        run: |
          # Adjust path if your build script outputs version somewhere else
          echo "version=$(cat build/version.txt)" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: socat-aarch64
          path: ./dist/socat-aarch64
